spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xing-shenglong/xingshenglong
          username: 15846344546
          password: sheng_568374
          timeout: 5
          default-label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 9100
